# Analise de Dados em Python

## Sumário

1. [Variáveis](#variáveis)
2. [Estrutura de decisão](#estrutura-de-decisão)
3. [Estruturas de repetição](#estruturas-de-repetição) 
    1. [while](#while)
    2. [for](#for)
    3. [brake](#brake)
    4. [continue](#continue)
4. [Listas](#listas)
5. [Dicionários, Sets e tuplas](#dicionários-sets-e-tuplas)
    1. [Dicionários](#dicionário)
    2. [Sets](#sets)
    3. [Tuplas](#tuplas)
6. [Numpy](#numpy)
    1. [Criar matriz unidimensional](#criar-matriz-unidimensional)
    2. [Criar matriz com um tipo específico](#criar-matriz-com-um-tipo-específico)
    3. [Mudar o tipo de array](#mudar-o-tipo-de-array)
    4. [Estrutura com mais de uma dimensão](#estrutura-com-mais-de-uma-dimensão)
    5. [Criar arrays vazios tipificados](#criar-arrays-vazios-tipificados)
    6. [Valores aleatórios](#valores-aleatórios)
    7. [Valores aleatórios com uso de sementes](#valores-aleatórios-com-uso-de-sementes)
    8. [Remover repetições](#remover-repetições)
    9. [Funções específicas](#funções-específicas)
    10. [Funções matemáticas](#funções-matemáticas)
    11. [Funções universais](#funções-universais)
    12. [Extração de elementos](#extração-de-elementos)
    13. [Extração de linhas e colunas](#extração-de-linhas-e-colunas)
    14. [Adição e multiplicação de matrizes](#adição-e-multiplicação-de-matrizes)
    15. [Transposição](#transposição)
    16. [Expressões lógicas](#expressões-lógicas)

## <a>Variáveis</a>

- Inteiro, real, string, boleano
- É case sensitive
- Boleano tem a primeira letra maiúscula (True / False)
- Converter entre tipos

In [10]:
# Converter de string para inteiro
var = input("Informe o valor")
print(type(var))
print(var)
var = int(var)
print(type(var))
print(var)

<class 'str'>
4
<class 'int'>
4


In [11]:
# Converter de string para real
var = input("Informe o valor")
print(type(var))
print(var)
var = float(var)
print(type(var))
print(var)

<class 'str'>
9
<class 'float'>
9.0


## <a>Estrutura de decisão</a>

Atenção a identação do código

In [19]:
nota = input("Informe nota")
nota =float(nota)
if nota < 0:
	print("Nota inválida!")
elif nota < 4:
	print("Reprovado")
elif nota >= 4 and nota < 6:
	print("Recuperação")
else:
	print("Aprovado")

Aprovado


## <a>Estruturas de repetição</a>

### <a>while</a>

In [20]:
count = 1
while count <= 5:
	print(count)
	count += 1

1
2
3
4
5


### <a>for</a>

- For decrescente;
- Range (inicio, parada, incremento);
- O python ignora o último valor de intervalos, no exemplo abaixo a parada será no número 0.

In [22]:
for n in range(10, 0, -1):
	print(n)

10
9
8
7
6
5
4
3
2
1


In [23]:
for n in range(0, 10):
	print(n)

0
1
2
3
4
5
6
7
8
9


### <a>brake</a>

- O brake irá interromper o laço quando o n for igual a 4.

In [24]:
for n in range(0, 10):
	if n==4:
		break
	print(n)

0
1
2
3


### <a>continue</a>

- O continue irá pular a impressão quando o n for igual a 4.

In [25]:
for n in range(0, 10):
	if n==4:
		continue
	print(n)

0
1
2
3
5
6
7
8
9


## <a>Listas</a>

- Formas de criar listas
- Um lista apenas com um tipo de dado

In [26]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


## Vários tipos

Uma lista com vários tipos de dados

In [1]:
lst = [1,2,3,"4",True]
print(lst)

[1, 2, 3, '4', True]


## Listas com listas

Uma lista que contém outra lista como um tipo de dado

In [2]:
lst = [12,[1,2,3,4,5],"a"]
print(lst)

[12, [1, 2, 3, 4, 5], 'a']


## Criando listas com range

Usando o range para criar uma lista, lembrando que o python ignora o último valor.

In [5]:
# De 0 a 9
lst = list(range(0,10))
print(lst)

# De 1 a 10
lst = list(range(1,11))
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## Comprimento da lista

In [6]:
print(len(lst))

10


## Acessando elemento

In [7]:
print(lst[0])

1


## Alterando posição

In [8]:
lst[0] = 9
print(lst)

[9, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## Percorrendo a lista

Percorre o vetor imprimindo o valor de cada posição.

In [9]:
for n in range(0, len(lst)):
	print(lst[n])

9
2
3
4
5
6
7
8
9
10


## <a>Dicionários, Sets e tuplas</a>

### <a>Dicionário</a>

Estrutura chave / valor.

In [10]:
Notas = {'João':6.0, 'Maria':8.0, 'Pedro':6.5}
print(Notas)

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}


Exibir todas as chaves

In [13]:
Notas.keys()

dict_keys(['João', 'Maria', 'Pedro'])

Exibir todos os valores

In [12]:
Notas.values()

dict_values([6.0, 8.0, 6.5])

Testar a existência de uma chave.

In [14]:
print('João' in Notas)
print('Fernando' in Notas)

True
False


Apagar um elemento.

In [15]:
del Notas['João']
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5}


Incluir um elemento.

In [16]:
Notas['Ana'] = 9
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}


Buscar um valor, se não encontrar mostrar o segundo parâmetro.

In [17]:
Notas.get('Geraldo',"Não encontrado")

'Não encontrado'

### <a>Sets</a>

São conjuntos não ordenados de elementos não repetidos.

In [19]:
bigdata = {'Spark','Hive','Sqoop'}
print(bigdata)

{'Sqoop', 'Hive', 'Spark'}


Verificar a existência de um elemento.

In [20]:
print('Spark' in bigdata)

True


Adicionar elemento.

In [21]:
bigdata.add('Hadoop')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

Exibir quantos elementos o set possui.

In [22]:
print(len(bigdata))

4


Não aceita adicionar elementos repetidos.

In [23]:
bigdata.add('Spark')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

### <a>Tuplas</a>

São listas que não podem ser alteradas.

Listas usam [] tuplas usam ().

In [24]:
tupla = (1,2,3,4,5,6,7)
tupla

(1, 2, 3, 4, 5, 6, 7)

Ler o elemento de determinada posição.

In [25]:
tupla[4]

5

Dicionários que em cada posição recebe uma tupla.

In [26]:
dic = {(0,1):0,(1,2):1,(2,3):2,(3,4):3,(4,5):4,(5,6):5,(6,7):6,(7,8):7,(8,9):8,(9,10):9}
dic

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [27]:
print(type(Notas))
print(type(bigdata))
print(type(tupla))

<class 'dict'>
<class 'set'>
<class 'tuple'>


## <a>Numpy</a>

É uma biblioteca utilizada para tratar dados.

In [28]:
# Importar a biblioteca
import numpy as np

### <a>Criar matriz unidimensional</a>

In [29]:
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


### <a>Criar matriz com um tipo específico</a>

In [30]:
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


### <a>Mudar o tipo de array</a>

In [31]:
mtnew = np.array([1.4,3.6,-5.1,9.42,4.99999])
print(mtnew)

# Transformar float para int os valores serão truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

# Transformar int para float
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]
[1 2 3 4]
[1. 2. 3. 4.]


### <a>Estrutura com mais de uma dimensão</a>

In [32]:
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


### <a>Criar arrays vazios tipificados</a>

In [33]:
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-----------------")

# criar uma matriz 4x3 com valores 0
zeros = np.zeros([4,3])
print(zeros)
print("-----------------")

# Com valores iguais a 1
um = np.ones([4,3])
print(um)
print("-----------------")

# cria matriz quadrada com diaggonal principal com valor 1 e outros com valor zero
diagonal = np.eye(5)
print(diagonal)

[[105801966245637               0]
 [134287664036208 134287674664688]
 [134287674726384 134287671416688]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### <a>Valores aleatórios</a>

In [34]:
# Entre zero e um
ale = np.random.random((5))
print(ale)
print("-----------------")

# Aleatórios contendo valores negativos
ale2 = np.random.randn((5))
print(ale2)
print("-----------------")

# Valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.20661355 0.46073645 0.98612756 0.76737346 0.4124651 ]
-----------------
[ 1.55542458 -1.36274793 -0.46253543  0.53352867 -0.24524852]
-----------------
[[6.91337734 4.19367123 2.76526888 9.3130208 ]
 [3.83325403 9.57147941 7.73438919 0.48854488]
 [9.8678184  2.31497078 0.09818222 6.17849919]]


### <a>Valores aleatórios com uso de sementes</a>

Os números são aleatórios, mas se rodar o código novamente os mesmos números serão gerados.

In [35]:
# Uso de sementes
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


### <a>Remover repetições</a>

In [36]:
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20,])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


### <a>Funções específicas</a>

In [37]:
# Criar a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

# Mostrar um elemento específico da matriz k
print(k[0][1])

# Mostrar o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


### <a>Funções matemáticas</a>

In [38]:
# Criar a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

# Exibir o maior valor
print(k.max())

# Exibir o menor valor
print(k.min())

# Exibir a soma dos valores da matriz
print(k.sum())

# Exibir a média dos valores da matriz
print(k.mean())

# Exibir o desvio padrão(standard deviation) dos valores da matriz
print(k.std())

[[17 22 43]
 [27 25 14]
 [15 24 32]]
43
14
219
24.333333333333332
8.615231988880057


### <a>Funções universais</a>

In [39]:
# Exibir a raiz quadrada de todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

# Exibir o valor do exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


### <a>Extração de elementos</a>

In [40]:
m = np.array(["a","b","c","d","e","f"])

# Exibir o elemento da posição 2
print(m[1])
print("-----------------")

# Exibir os elementos da posição 0 até 2, lembrando que em intervalos no Python o último elemento é ignorado
print(m[0:2])
print("-----------------")

# Exibir todos os elementos a partir do elemento informado
print(m[1:])
print("-----------------")

# Exibir o array criado a partir do número negativo até o final, por exemplo, se um array tem 10 elementos e informamos -3, então ele vai imprimir o elemento 8, 9 e 10.
print(m[-3:])

b
-----------------
['a' 'b']
-----------------
['b' 'c' 'd' 'e' 'f']
-----------------
['d' 'e' 'f']


### <a>Extração de linhas e colunas</a>

In [41]:
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("-----------------")

# Primeira linha, todas as colunas
l_linha_1 = l[0,:]
print(l_linha_1)
print("-----------------")

# Segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)
print("-----------------")

# terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)
print("-----------------")

# Todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("-----------------")

# Todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-----------------
[4 5]
-----------------
[6 1]
-----------------
[7 4]
-----------------
[4 6 7]
-----------------
[5 1 4]


### <a>Adição e multiplicação de matrizes</a>

In [42]:
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])

res1 = n+o
print(res1)
print("-----------------")

res2 = n*o
print(res2)
print("-----------------")

p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-----------------
[[1 2]
 [3 4]]
-----------------
[[3 3]
 [5 5]
 [7 7]]


### <a>Transposição</a>

In [43]:
# Criar uma matriz 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))

# Exibir a matriz transposta entre linhas e colunas
print(f)
print("-----------------")

s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [44]:
# Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))

# Exibir a matriz transposta entre linhas e colunas
print(r)
print("-----------------")

# Exibir a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### <a>Expressões lógicas</a>

In [45]:
# Criar matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)

# Criar matriz com valores booleanos baseados no array v
x = (v > 0)
print(x)

# Criar matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x >0, 1, -1)
print(z)

[[ 0.58578813  1.01354749  0.30880437  0.77483877]
 [ 0.16672686  0.37462009  0.09672634  1.54109611]
 [-0.45054043 -0.41200607  1.79009229 -1.11519265]
 [ 0.76567982  0.77714575 -0.29010933  0.10431752]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False  True False]
 [ True  True False  True]]
[[ 1  1  1  1]
 [ 1  1  1  1]
 [-1 -1  1 -1]
 [ 1  1 -1  1]]
