# Analise de Dados em Python

## Sumário

1. [Variáveis](#variáveis)
2. [Estrutura de decisão](#estrutura-de-decisão)
3. [Estruturas de repetição](#estruturas-de-repetição) 
    1. [while](#while)
    2. [for](#for)
    3. [brake](#brake)
    4. [continue](#continue)
4. [Listas](#listas)
5. [Dicionários, Sets e tuplas](#dicionários-sets-e-tuplas)
    1. [Dicionários](#dicionário)
    2. [Sets](#sets)
    3. [Tuplas](#tuplas)
6. [Numpy](#numpy)
    1. [Criar matriz unidimensional](#criar-matriz-unidimensional)
    2. [Criar matriz com um tipo específico](#criar-matriz-com-um-tipo-específico)
    3. [Mudar o tipo de array](#mudar-o-tipo-de-array)
    4. [Estrutura com mais de uma dimensão](#estrutura-com-mais-de-uma-dimensão)
    5. [Criar arrays vazios tipificados](#criar-arrays-vazios-tipificados)
    6. [Valores aleatórios](#valores-aleatórios)
    7. [Valores aleatórios com uso de sementes](#valores-aleatórios-com-uso-de-sementes)
    8. [Remover repetições](#remover-repetições)
    9. [Funções específicas](#funções-específicas)
    10. [Funções matemáticas](#funções-matemáticas)
    11. [Funções universais](#funções-universais)
    12. [Extração de elementos](#extração-de-elementos)
    13. [Extração de linhas e colunas](#extração-de-linhas-e-colunas)
    14. [Adição e multiplicação de matrizes](#adição-e-multiplicação-de-matrizes)
    15. [Transposição](#transposição)
    16. [Expressões lógicas](#expressões-lógicas)
7. [Pandas](#pandas)
    1. [Importação da biblioteca](#importação-da-biblioteca)
    2. [Carregar um dataframe](#carregar-um-dataframe)
    3. [Resumo estatístico de colunas numéricas](#resumo-estatístico-de-colunas-numéricas)
    4. [Exibir primeiros registros](#exibir-primeiros-registros)
    5. [Exibir últimos registros](#exibir-últimos-registros)
    6. [Filtrar por coluna](#filtrar-por-coluna)
    7. [Filtrar linha por índice](#filtrar-linha-por-índice)
    8. [Filtrar por linhas específicas](#filtrar-por-linhas-específicas)
    9. [Filtrar](#filtrar)
    10. [Atribuir variáveis filtradas a um novo dataframe](#atribuir-variáveis-filtradas-a-um-novo-dataframe)
    11. [Atribuir apenas algumas colunas](#atribuir-apenas-algumas-colunas)
    12. [Séries, única coluna](#séries-única-coluna)
    13. [Série a partir de um array do numpy](#série-a-partir-de-um-array-do-numpy)
    14. [Série a partir de um dataframe](#série-a-partir-de-um-dataframe)
    15. [Diferença entre série e dataframe](#diferença-entre-série-e-dataframe)
    16. [Renomear variáveis](#renomear-variáveis)
    17. [Persistindo os nomes renomeados](#persistindo-os-nomes-renomeados)
    18. [Excluir coluna](#excluir-coluna)
    19. [Verificar dados nulos](#verificar-dados-nulos)
    20. [Verificar dados nulos com maior precisão](#verificar-dados-nulos-com-maior-precisãori)
    21. [Remover colunas com NaN](#remover-colunas-com-nan)
    22. [Preencher dados faltantes](#preencher-dados-faltantes)
    23. [iloc - Intervalos de linhas e colunas](#iloc---intervalos-de-linhas-e-colunas)


















## <a>Variáveis</a>

- Inteiro, real, string, boleano
- É case sensitive
- Boleano tem a primeira letra maiúscula (True / False)
- Converter entre tipos

In [77]:
# Converter de string para inteiro
var = input("Informe o valor")
print(type(var))
print(var)
var = int(var)
print(type(var))
print(var)

<class 'str'>
4
<class 'int'>
4


In [78]:
# Converter de string para real
var = input("Informe o valor")
print(type(var))
print(var)
var = float(var)
print(type(var))
print(var)

<class 'str'>
7
<class 'float'>
7.0


## <a>Estrutura de decisão</a>

Atenção a identação do código

In [79]:
nota = input("Informe nota")
nota =float(nota)
if nota < 0:
	print("Nota inválida!")
elif nota < 4:
	print("Reprovado")
elif nota >= 4 and nota < 6:
	print("Recuperação")
else:
	print("Aprovado")

Recuperação


## <a>Estruturas de repetição</a>

### <a>while</a>

In [80]:
count = 1
while count <= 5:
	print(count)
	count += 1

1
2
3
4
5


### <a>for</a>

- For decrescente;
- Range (inicio, parada, incremento);
- O python ignora o último valor de intervalos, no exemplo abaixo a parada será no número 0.

In [81]:
for n in range(10, 0, -1):
	print(n)

10
9
8
7
6
5
4
3
2
1


In [82]:
for n in range(0, 10):
	print(n)

0
1
2
3
4
5
6
7
8
9


### <a>brake</a>

- O brake irá interromper o laço quando o n for igual a 4.

In [83]:
for n in range(0, 10):
	if n==4:
		break
	print(n)

0
1
2
3


### <a>continue</a>

- O continue irá pular a impressão quando o n for igual a 4.

In [84]:
for n in range(0, 10):
	if n==4:
		continue
	print(n)

0
1
2
3
5
6
7
8
9


## <a>Listas</a>

- Formas de criar listas
- Um lista apenas com um tipo de dado

In [85]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


## Vários tipos

Uma lista com vários tipos de dados

In [86]:
lst = [1,2,3,"4",True]
print(lst)

[1, 2, 3, '4', True]


## Listas com listas

Uma lista que contém outra lista como um tipo de dado

In [87]:
lst = [12,[1,2,3,4,5],"a"]
print(lst)

[12, [1, 2, 3, 4, 5], 'a']


## Criando listas com range

Usando o range para criar uma lista, lembrando que o python ignora o último valor.

In [88]:
# De 0 a 9
lst = list(range(0,10))
print(lst)

# De 1 a 10
lst = list(range(1,11))
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## Comprimento da lista

In [89]:
print(len(lst))

10


## Acessando elemento

In [90]:
print(lst[0])

1


## Alterando posição

In [91]:
lst[0] = 9
print(lst)

[9, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## Percorrendo a lista

Percorre o vetor imprimindo o valor de cada posição.

In [92]:
for n in range(0, len(lst)):
	print(lst[n])

9
2
3
4
5
6
7
8
9
10


## <a>Dicionários, Sets e tuplas</a>

### <a>Dicionário</a>

Estrutura chave / valor.

In [93]:
Notas = {'João':6.0, 'Maria':8.0, 'Pedro':6.5}
print(Notas)

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}


Exibir todas as chaves

In [94]:
Notas.keys()

dict_keys(['João', 'Maria', 'Pedro'])

Exibir todos os valores

In [95]:
Notas.values()

dict_values([6.0, 8.0, 6.5])

Testar a existência de uma chave.

In [96]:
print('João' in Notas)
print('Fernando' in Notas)

True
False


Apagar um elemento.

In [97]:
del Notas['João']
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5}


Incluir um elemento.

In [98]:
Notas['Ana'] = 9
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}


Buscar um valor, se não encontrar mostrar o segundo parâmetro.

In [99]:
Notas.get('Geraldo',"Não encontrado")

'Não encontrado'

### <a>Sets</a>

São conjuntos não ordenados de elementos não repetidos.

In [100]:
bigdata = {'Spark','Hive','Sqoop'}
print(bigdata)

{'Sqoop', 'Hive', 'Spark'}


Verificar a existência de um elemento.

In [101]:
print('Spark' in bigdata)

True


Adicionar elemento.

In [102]:
bigdata.add('Hadoop')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

Exibir quantos elementos o set possui.

In [103]:
print(len(bigdata))

4


Não aceita adicionar elementos repetidos.

In [104]:
bigdata.add('Spark')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

### <a>Tuplas</a>

São listas que não podem ser alteradas.

Listas usam [] tuplas usam ().

In [105]:
tupla = (1,2,3,4,5,6,7)
tupla

(1, 2, 3, 4, 5, 6, 7)

Ler o elemento de determinada posição.

In [106]:
tupla[4]

5

Dicionários que em cada posição recebe uma tupla.

In [107]:
dic = {(0,1):0,(1,2):1,(2,3):2,(3,4):3,(4,5):4,(5,6):5,(6,7):6,(7,8):7,(8,9):8,(9,10):9}
dic

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [108]:
print(type(Notas))
print(type(bigdata))
print(type(tupla))

<class 'dict'>
<class 'set'>
<class 'tuple'>


## <a>Numpy</a>

É uma biblioteca utilizada para tratar dados.

In [109]:
# Importar a biblioteca
import numpy as np

### <a>Criar matriz unidimensional</a>

In [110]:
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


### <a>Criar matriz com um tipo específico</a>

In [111]:
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


### <a>Mudar o tipo de array</a>

In [112]:
mtnew = np.array([1.4,3.6,-5.1,9.42,4.99999])
print(mtnew)

# Transformar float para int os valores serão truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

# Transformar int para float
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]
[1 2 3 4]
[1. 2. 3. 4.]


### <a>Estrutura com mais de uma dimensão</a>

In [113]:
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


### <a>Criar arrays vazios tipificados</a>

In [114]:
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-----------------")

# criar uma matriz 4x3 com valores 0
zeros = np.zeros([4,3])
print(zeros)
print("-----------------")

# Com valores iguais a 1
um = np.ones([4,3])
print(um)
print("-----------------")

# cria matriz quadrada com diaggonal principal com valor 1 e outros com valor zero
diagonal = np.eye(5)
print(diagonal)

[[   6   48]
 [1169 5951]
 [   4    2]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### <a>Valores aleatórios</a>

In [115]:
# Entre zero e um
ale = np.random.random((5))
print(ale)
print("-----------------")

# Aleatórios contendo valores negativos
ale2 = np.random.randn((5))
print(ale2)
print("-----------------")

# Valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.6310312  0.42566474 0.36525466 0.9426821  0.99962955]
-----------------
[ 0.51296577 -1.01266572  0.8877263   0.61148741 -1.95525818]
-----------------
[[9.2774954  6.10251395 4.81777406 1.75329037]
 [4.29808776 0.16839674 8.71195033 1.59988076]
 [9.83811326 2.7110813  9.61381038 2.48694307]]


### <a>Valores aleatórios com uso de sementes</a>

Os números são aleatórios, mas se rodar o código novamente os mesmos números serão gerados.

In [116]:
# Uso de sementes
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


### <a>Remover repetições</a>

In [117]:
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20,])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


### <a>Funções específicas</a>

In [118]:
# Criar a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

# Mostrar um elemento específico da matriz k
print(k[0][1])

# Mostrar o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


### <a>Funções matemáticas</a>

In [119]:
# Criar a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

# Exibir o maior valor
print(k.max())

# Exibir o menor valor
print(k.min())

# Exibir a soma dos valores da matriz
print(k.sum())

# Exibir a média dos valores da matriz
print(k.mean())

# Exibir o desvio padrão(standard deviation) dos valores da matriz
print(k.std())

[[17 22 43]
 [27 25 14]
 [15 24 32]]
43
14
219
24.333333333333332
8.615231988880057


### <a>Funções universais</a>

In [120]:
# Exibir a raiz quadrada de todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

# Exibir o valor do exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


### <a>Extração de elementos</a>

In [121]:
m = np.array(["a","b","c","d","e","f"])

# Exibir o elemento da posição 2
print(m[1])
print("-----------------")

# Exibir os elementos da posição 0 até 2, lembrando que em intervalos no Python o último elemento é ignorado
print(m[0:2])
print("-----------------")

# Exibir todos os elementos a partir do elemento informado
print(m[1:])
print("-----------------")

# Exibir o array criado a partir do número negativo até o final, por exemplo, se um array tem 10 elementos e informamos -3, então ele vai imprimir o elemento 8, 9 e 10.
print(m[-3:])

b
-----------------
['a' 'b']
-----------------
['b' 'c' 'd' 'e' 'f']
-----------------
['d' 'e' 'f']


### <a>Extração de linhas e colunas</a>

In [122]:
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("-----------------")

# Primeira linha, todas as colunas
l_linha_1 = l[0,:]
print(l_linha_1)
print("-----------------")

# Segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)
print("-----------------")

# terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)
print("-----------------")

# Todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("-----------------")

# Todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-----------------
[4 5]
-----------------
[6 1]
-----------------
[7 4]
-----------------
[4 6 7]
-----------------
[5 1 4]


### <a>Adição e multiplicação de matrizes</a>

In [123]:
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])

res1 = n+o
print(res1)
print("-----------------")

res2 = n*o
print(res2)
print("-----------------")

p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-----------------
[[1 2]
 [3 4]]
-----------------
[[3 3]
 [5 5]
 [7 7]]


### <a>Transposição</a>

In [124]:
# Criar uma matriz 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))

# Exibir a matriz transposta entre linhas e colunas
print(f)
print("-----------------")

s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [125]:
# Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))

# Exibir a matriz transposta entre linhas e colunas
print(r)
print("-----------------")

# Exibir a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### <a>Expressões lógicas</a>

In [126]:
# Criar matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)

# Criar matriz com valores booleanos baseados no array v
x = (v > 0)
print(x)

# Criar matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x >0, 1, -1)
print(z)

[[ 0.58345506 -0.26181305 -0.72471694  0.39498859]
 [ 0.56490771  1.1389714   0.21130885 -0.49902057]
 [-1.32559031  1.4682839  -1.11890481  0.89064603]
 [-0.0221965   2.14140802 -0.55398897 -0.15043166]]
[[ True False False  True]
 [ True  True  True False]
 [False  True False  True]
 [False  True False False]]
[[ 1 -1 -1  1]
 [ 1  1  1 -1]
 [-1  1 -1  1]
 [-1  1 -1 -1]]


## <a>Pandas</a>

O Pandas é uma biblioteca utilizada para tratar dados tabulares, ou seja, dados distribuídos em linhas e colunas.

### <a>Importação da biblioteca</a>

In [127]:
# No terminal rodar o seguinte comando da primeira vez que executar:
# pip install pandas 

import pandas as pd

### <a>Carregar um dataframe</a>

In [128]:
dados = pd.read_csv("~/Desenvolvimento/Udemy_Formacao_Cientista_de_Dados/7.Prática em Python/dados/Credit.csv")
dados.shape

(1000, 21)

### <a>Resumo estatístico de colunas numéricas</a>

In [129]:
dados.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

### <a>Exibir primeiros registros</a>

In [130]:
dados.head()

checking_status  duration                    credit_history  \
0              <0         6  'critical/other existing credit'   
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'        >=7   
1             radio/tv           5951                <100     1<=X<4   
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

### <a>Exibir últimos registros</a>

In [131]:
dados.tail(2)

checking_status  duration                    credit_history     purpose  \
998              <0        45                   'existing paid'    radio/tv   
999        0<=X<200        45  'critical/other existing credit'  'used car'   

     credit_amount savings_status  employment  installment_commitment  \
998           1845           <100      1<=X<4                       4   
999           4576     100<=X<500  unemployed                       3   

    personal_status other_parties  ...   property_magnitude age  \
998   'male single'          none  ...  'no known property'  23   
999   'male single'          none  ...                  car  27   

     other_payment_plans     housing existing_credits      job num_dependents  \
998                 none  'for free'                1  skilled              1   
999                 none         own                1  skilled              1   

     own_telephone foreign_worker class  
998            yes            yes   bad  
999           none            yes  good  

[2 rows x 21 columns]

### <a>Filtrar por coluna</a>

In [132]:
dados[["duration"]]

duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

### <a>Filtrar linha por índice</a>

In [133]:
dados.loc[1:3]

checking_status  duration                    credit_history  \
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   

               purpose  credit_amount savings_status employment  \
1             radio/tv           5951           <100     1<=X<4   
2            education           2096           <100     4<=X<7   
3  furniture/equipment           7882           <100     4<=X<7   

   installment_commitment       personal_status other_parties  ...  \
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   

   property_magnitude age  other_payment_plans     housing existing_credits  \
1       'real estate'  22                 none         own                1   
2       'real estate'  49                 none         own                1   
3    'life insurance'  45                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  

[3 rows x 21 columns]

### <a>Filtrar por linhas específicas</a>

In [134]:
dados.loc[[1,3]]

checking_status  duration   credit_history              purpose  \
1        0<=X<200        48  'existing paid'             radio/tv   
3              <0        42  'existing paid'  furniture/equipment   

   credit_amount savings_status employment  installment_commitment  \
1           5951           <100     1<=X<4                       2   
3           7882           <100     4<=X<7                       2   

        personal_status other_parties  ...  property_magnitude age  \
1  'female div/dep/mar'          none  ...       'real estate'  22   
3         'male single'     guarantor  ...    'life insurance'  45   

   other_payment_plans     housing existing_credits      job num_dependents  \
1                 none         own                1  skilled              1   
3                 none  'for free'                1  skilled              2   

   own_telephone foreign_worker class  
1           none            yes   bad  
3           none            yes  good  

[2 rows x 21 columns]

### <a>Filtrar</a>

In [135]:
# Exemplo 1
dados.loc[dados['purpose'] == "radio/tv"]

checking_status  duration                    credit_history   purpose  \
0                <0         6  'critical/other existing credit'  radio/tv   
1          0<=X<200        48                   'existing paid'  radio/tv   
8     'no checking'        12                   'existing paid'  radio/tv   
12         0<=X<200        12                   'existing paid'  radio/tv   
15               <0        24                   'existing paid'  radio/tv   
..              ...       ...                               ...       ...   
989        0<=X<200        24  'critical/other existing credit'  radio/tv   
991   'no checking'        15                        'all paid'  radio/tv   
992              <0        18                   'existing paid'  radio/tv   
997   'no checking'        12                   'existing paid'  radio/tv   
998              <0        45                   'existing paid'  radio/tv   

     credit_amount      savings_status employment  installment_commitment  \
0             1169  'no known savings'        >=7                       4   
1             5951                <100     1<=X<4                       2   
8             3059              >=1000     4<=X<7                       2   
12            1567                <100     1<=X<4                       1   
15            1282          100<=X<500     1<=X<4                       4   
..             ...                 ...        ...                     ...   
989           1743                <100        >=7                       4   
991           1569          100<=X<500        >=7                       4   
992           1936  'no known savings'     4<=X<7                       2   
997            804                <100        >=7                       4   
998           1845                <100     1<=X<4                       4   

          personal_status other_parties  ...   property_magnitude age  \
0           'male single'          none  ...        'real estate'  67   
1    'female div/dep/mar'          none  ...        'real estate'  22   
8          'male div/sep'          none  ...        'real estate'  61   
12   'female div/dep/mar'          none  ...                  car  22   
15   'female div/dep/mar'          none  ...                  car  32   
..                    ...           ...  ...                  ...  ..   
989         'male single'          none  ...     'life insurance'  48   
991         'male single'          none  ...                  car  34   
992        'male mar/wid'          none  ...                  car  23   
997         'male single'          none  ...                  car  38   
998         'male single'          none  ...  'no known property'  23   

     other_payment_plans     housing existing_credits                   job  \
0                   none         own                2               skilled   
1                   none         own                1               skilled   
8                   none         own                1  'unskilled resident'   
12                  none         own                1               skilled   
15                  none         own                1  'unskilled resident'   
..                   ...         ...              ...                   ...   
989                 none         own                2  'unskilled resident'   
991                 bank         own                1  'unskilled resident'   
992                 none        rent                2  'unskilled resident'   
997                 none         own                1               skilled   
998                 none  'for free'                1               skilled   

    num_dependents  own_telephone foreign_worker class  
0                1            yes            yes  good  
1                1           none            yes   bad  
8                1           none            yes  good  
12               1            yes            yes  good  
15               1           none          

In [136]:
# Exemplo 2
dados.loc[dados['credit_amount'] > 18000]

checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]

### <a>Atribuir variáveis filtradas a um novo dataframe</a>

In [137]:
credito2 = dados.loc[dados['credit_amount'] > 18000]
print(credito2)

    checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]


### <a>Atribuir apenas algumas colunas</a>

In [138]:
credito3 = dados[['checking_status', 'duration']].loc[dados['credit_amount'] > 18000]
print(credito3)

    checking_status  duration
915        0<=X<200        48


### <a>Séries, única coluna</a>

Pode ser crriada a partir de listas, array do numpy ou coluna de data frame

In [139]:
s1 = pd.Series([2,5,3,34,54,23,1,16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


### <a>Série a partir de um array do numpy</a>

In [140]:
import numpy as np
array1 = np.array([2,5,3,34,54,23,1,16])
s2 = pd.Series(array1)
print(s2)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


### <a>Série a partir de um dataframe</a>

In [141]:
s3 = dados['purpose']
print(s3)
type(s3)

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...         
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object


pandas.core.series.Series

### <a>Diferença entre série e dataframe</a>

In [142]:
d4 = dados[['purpose']]
type(d4)

pandas.core.frame.DataFrame

### <a>Renomear variáveis</a>

In [143]:
dados.rename(columns={"duration":"duração","purpose":"propósito"})
# A alteração anterior não foi persistida
dados.head(2)

checking_status  duration                    credit_history   purpose  \
0              <0         6  'critical/other existing credit'  radio/tv   
1        0<=X<200        48                   'existing paid'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   
1           5951                <100     1<=X<4                       2   

        personal_status other_parties  ...  property_magnitude age  \
0         'male single'          none  ...       'real estate'  67   
1  'female div/dep/mar'          none  ...       'real estate'  22   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   
1                 none     own                1  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  
1           none            yes   bad  

[2 rows x 21 columns]

### <a>Persistindo os nomes renomeados</a>

Vários métodos do Pandas utilizam o parametro inplace=True para definir que a alteração seja persistida.

In [144]:
dados.rename(columns={"duration":"duração","purpose":"propósito"},inplace=True)
dados.head(2)

checking_status  duração                    credit_history propósito  \
0              <0        6  'critical/other existing credit'  radio/tv   
1        0<=X<200       48                   'existing paid'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   
1           5951                <100     1<=X<4                       2   

        personal_status other_parties  ...  property_magnitude age  \
0         'male single'          none  ...       'real estate'  67   
1  'female div/dep/mar'          none  ...       'real estate'  22   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   
1                 none     own                1  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  
1           none            yes   bad  

[2 rows x 21 columns]

### <a>Excluir coluna</a>

In [145]:
dados.drop('checking_status',axis=1,inplace=True)
print(dados)
dados.head(2)

     duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                   

duração                    credit_history propósito  credit_amount  \
0        6  'critical/other existing credit'  radio/tv           1169   
1       48                   'existing paid'  radio/tv           5951   

       savings_status employment  installment_commitment  \
0  'no known savings'        >=7                       4   
1                <100     1<=X<4                       2   

        personal_status other_parties  residence_since property_magnitude  \
0         'male single'          none                4      'real estate'   
1  'female div/dep/mar'          none                2      'real estate'   

   age other_payment_plans housing  existing_credits      job  num_dependents  \
0   67                none     own                 2  skilled               1   
1   22                none     own                 1  skilled               1   

  own_telephone foreign_worker class  
0           yes            yes  good  
1          none            yes   bad

### <a>Verificar dados nulos</a>

In [146]:
dados.isnull()

duração  credit_history  propósito  credit_amount  savings_status  \
0      False           False      False          False           False   
1      False           False      False          False           False   
2      False           False      False          False           False   
3      False           False      False          False           False   
4      False           False      False          False           False   
..       ...             ...        ...            ...             ...   
995    False           False      False          False           False   
996    False           False      False          False           False   
997    False           False      False          False           False   
998    False           False      False          False           False   
999    False           False      False          False           False   

     employment  installment_commitment  personal_status  other_parties  \
0         False                   False            False          False   
1         False                   False            False          False   
2         False                   False            False          False   
3         False                   False            False          False   
4         False                   False            False          False   
..          ...                     ...              ...            ...   
995       False                   False            False          False   
996       False                   False            False          False   
997       False                   False            False          False   
998       False                   False            False          False   
999       False                   False            False          False   

     residence_since  property_magnitude    age  other_payment_plans  housing  \
0              False               False  False                False    False   
1              False               False  False                False    False   
2              False               False  False                False    False   
3              False               False  False                False    False   
4              False               False  False                False    False   
..               ...                 ...    ...                  ...      ...   
995            False               False  False                False    False   
996            False               False  False                False    False   
997            False               False  False                False    False   
998            False               False  False                False    False   
999            False               False  False                False    False   

     existing_credits    job  num_dependents  own_telephone  foreign_worker  \
0               False  False           False          False           False   
1               False  False           False          False           False   
2               False  False           False          False           False   
3               False  False           False          False           False   
4               False  False           False          False           False   
..                ...    ...             ...            ...             ...   
995             False  False           False          False           False   
996             False  False           False          False           False   
997             False  False           False          False           False   
998             False  False           False          False           False   
999             False  False           False          False           False   

     class  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
995  False  
996  False  
997  False  
998  False  
999  False  

[1000 rows x 20 columns]

### <a>Verificar dados nulos com maior precisão</a>

In [147]:
dados.isnull().sum()

duração                   0
credit_history            0
propósito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

### <a>Remover colunas com NaN</a>

In [148]:
dados.dropna()

duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4   
1             5951                <100      1<=X<4                       2   
2             2096                <100      4<=X<7                       2   
3             7882                <100      4<=X<7                       2   
4             4870                <100      1<=X<4                       3   
..             ...                 ...         ...                     ...   
995           1736                <100      4<=X<7                       3   
996           3857                <100      1<=X<4                       4   
997            804                <100         >=7                       4   
998           1845                <100      1<=X<4                       4   
999           4576          100<=X<500  unemployed                       3   

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'   
1    'female div/dep/mar'          none                2        'real estate'   
2           'male single'          none                3        'real estate'   
3           'male single'     guarantor                4     'life insurance'   
4           'male single'          none                4  'no known property'   
..                    ...           ...              ...                  ...   
995  'female div/dep/mar'          none                4        'real estate'   
996        'male div/sep'          none                4     'life insurance'   
997         'male single'          none                4                  car   
998         'male single'          none                4  'no known property'   
999         'male single'          none                4                  car   

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2   
1     22                none         own                 1   
2     49                none         own                 1   
3     45                none  'for free'                 1   
4     53                none  'for free'                 2   
..   ...                 ...         ...               ...   
995   31                none         own                 1   
996   40                none         own                 1   
997   38                none         own                 1   
998   23                none  'for free'                 1   
999   27                none         own                 1   

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes   
1                        skilled               1          none            yes   
2           'unskilled resident'               2          none            yes   
3                        skilled               2          none            yes   
4                        skilled               2          none            yes   
..         

### <a>Preencher dados faltantes</a>

Sendo que o zero é o valor que iremos utilizar para preencher as células faltantes

In [ ]:
dados['duração'].fillna(0,inplace=True)

### <a>iloc - Intervalos de linhas e colunas</a>

In [150]:
# [linha inicial:final, coluna inicial: final]
dados.iloc[0:3,0:5]

duração                    credit_history  propósito  credit_amount  \
0        6  'critical/other existing credit'   radio/tv           1169   
1       48                   'existing paid'   radio/tv           5951   
2       12  'critical/other existing credit'  education           2096   

       savings_status  
0  'no known savings'  
1                <100  
2                <100

In [151]:
# [[uma lista com as linhas], coluna inicial: final]
dados.iloc[[0,1,2,3,7],0:5]

duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
7       36                   'existing paid'           'used car'   

   credit_amount      savings_status  
0           1169  'no known savings'  
1           5951                <100  
2           2096                <100  
3           7882                <100  
7           6948                <100